const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const source = fs.readFileSync(path.resolve(__dirname, '../suris-ecoflow-flow-card.js'), 'utf8');
const registry = new Map();
const context = { HTMLElement: class {}, window: {}, console: { info() {} }, customElements: { get: key => registry.get(key), define: (key, value) => registry.set(key, value) } };
vm.createContext(context);
vm.runInContext(source.replace('  class SurisEcoFlowFlowCard extends HTMLElement {', '  globalThis.api = { model, merge, readNumber, flowSpeed, selectConsumers };\n  class SurisEcoFlowFlowCard extends HTMLElement {'), context);
const { model, merge, readNumber, flowSpeed, selectConsumers } = context.api;
const config = merge({grid:{power:'sensor.grid',available_entity:'binary_sensor.grid',available_state:'on'},auxiliary_1:{input_power:'sensor.a_in',output_power:'sensor.a_out'},auxiliary_2:{input_power:'sensor.b_in',output_power:'sensor.b_out'},main:{input_power:'sensor.m_in',output_power:'sensor.m_out',ac_input_power:'sensor.m_ac',solar_input_power:'sensor.m_pv'},home:{power:'sensor.home',source_entity:'binary_sensor.source',grid_state:'on',main_state:'off'}});
const states = {};
const set = (id, value, unit='W') => states[id] = {state:String(value),attributes:{unit_of_measurement:unit}};
const flow = () => JSON.parse(JSON.stringify(model(config,states).flows));
set('sensor.grid',0);set('binary_sensor.grid','off');set('binary_sensor.source','off');
set('sensor.a_in',0);set('sensor.b_in',0);set('sensor.a_out',150);set('sensor.b_out',200);
set('sensor.m_in',.33,'kW');set('sensor.m_ac',0);set('sensor.m_pv',330);set('sensor.m_out',320);set('sensor.home',320);
assert.deepEqual(flow(),{grid_auxiliary_1:false,grid_auxiliary_2:false,grid_main:false,auxiliary_1_main:true,auxiliary_2_main:true,grid_home:false,main_home:true});
assert.equal(model(config,states).main.input,330);
set('binary_sensor.source','on');set('binary_sensor.grid','on');set('sensor.a_in',100);set('sensor.b_in',200);set('sensor.m_ac',300);
assert(flow().grid_home);assert(!flow().main_home);assert(flow().grid_main);assert(flow().grid_auxiliary_1);assert(flow().grid_auxiliary_2);
for(const state of ['unknown','unavailable','unexpected','']){set('binary_sensor.grid',state);assert(!flow().grid_home);assert(!flow().main_home)}
set('binary_sensor.grid','on');set('sensor.m_pv','unavailable');assert(flow().auxiliary_1_main);assert(flow().auxiliary_2_main);
set('sensor.m_ac','unavailable');assert(!flow().grid_main);assert.equal(model(config,states).main.ac,null);
set('sensor.a_in','unknown');assert(!flow().grid_auxiliary_1);
set('sensor.m_ac',3);assert(!flow().grid_main);set('sensor.m_ac',3.01);assert(flow().grid_main);
set('sensor.m_ac',100);set('sensor.m_pv',200);delete config.main.input_power;assert.equal(model(config,states).main.input,300);
set('sensor.m_pv','unavailable');assert.equal(model(config,states).main.input,null);
set('sensor.m_pv',2,'kWh');assert.equal(model(config,states).main.solar_1,null);
set('sensor.m_ac',1000,'mW');assert.equal(model(config,states).main.ac,1);
set('sensor.m_ac',.001,'MW');assert.equal(model(config,states).main.ac,1000);
set('sensor.a_in','');assert.equal(readNumber(states,'sensor.a_in',true),null);
set('sensor.a_in',-10);assert(!flow().grid_auxiliary_1);
set('binary_sensor.grid','off');delete config.home.power;assert(flow().main_home);config.home.power='sensor.home';set('sensor.home','unavailable');assert(!flow().main_home);
assert.doesNotThrow(()=>merge({home:{grid_state:'on',main_state:'on'}}));
assert.throws(()=>merge({appearance:{threshold:-1}}));assert.throws(()=>merge({appearance:{duration:0}}));assert.throws(()=>merge({appearance:{grid_color:'red'}}));
delete config.home.power;
set('binary_sensor.source','on');set('binary_sensor.grid','on');set('sensor.grid',1,'kW');
set('sensor.a_in',100);set('sensor.b_in',200);set('sensor.m_ac',300);
assert.equal(model(config,states).home.power,400);assert.equal(model(config,states).home.power_origin,'grid_balance');
assert(flow().grid_home);assert(!flow().main_home);
set('sensor.b_in','unavailable');assert.equal(model(config,states).home.power,600);assert(flow().grid_home);
for(const value of ['unavailable','unknown','']){set('sensor.a_in',value);set('sensor.b_in',value);set('sensor.m_ac',value);assert.equal(model(config,states).home.power,1000);assert(flow().grid_home);assert(!flow().grid_main)}
set('sensor.grid','unavailable');assert.equal(model(config,states).home.power,null);assert(!flow().grid_home);
set('sensor.grid',1000);set('sensor.a_in',100);set('sensor.m_ac',300);
set('sensor.b_in',200);set('sensor.grid',100);assert.equal(model(config,states).home.power,0);assert(!flow().grid_home);
set('binary_sensor.grid','off');set('sensor.m_out',320);assert.equal(model(config,states).home.power,320);assert(flow().main_home);
config.main.home_feed_power='sensor.feed';set('sensor.feed',275);assert.equal(model(config,states).home.power,275);
set('sensor.feed','unavailable');assert.equal(model(config,states).home.power,null);assert(!flow().main_home);
set('binary_sensor.grid','unexpected');assert.equal(model(config,states).home.power,null);assert(!flow().main_home);assert(!flow().grid_home);
config.home.power='sensor.home';set('sensor.home',123);assert.equal(model(config,states).home.power,123);assert.equal(model(config,states).home.power_origin,'sensor');
set('sensor.home','unavailable');assert.equal(model(config,states).home.power,null);
delete config.home.power;delete config.main.home_feed_power;
set('binary_sensor.grid','off');assert.equal(model(config,states).home.source,'main');
config.grid.available_state='off';assert.equal(model(config,states).home.source,'grid');
set('binary_sensor.grid','on');assert.equal(model(config,states).home.source,'main');
config.grid.available_state='on';set('binary_sensor.grid','on');assert.equal(model(config,states).home.source,'grid');
set('sensor.grid',0);assert.equal(model(config,states).home.source,'grid');
for(const value of ['unknown','unavailable','']){set('binary_sensor.grid',value);assert.equal(model(config,states).home.source,'unknown')}
delete config.grid.available_entity;assert.equal(model(config,states).home.source,'unknown');
const gridOnly=merge({grid:{power:'sensor.grid',available_entity:'binary_sensor.grid'}});
set('binary_sensor.grid','on');set('sensor.grid',285);assert.equal(model(gridOnly,states).home.power,285);assert(model(gridOnly,states).flows.grid_home);
gridOnly.auxiliary_1.input_power='sensor.a_in';set('sensor.a_in',50);assert.equal(model(gridOnly,states).home.power,235);
set('sensor.a_in',0);assert.equal(model(gridOnly,states).home.power,285);
set('sensor.a_in',-10);assert.equal(model(gridOnly,states).home.power,285);
const blank=model(merge({}),{});assert(Object.values(blank.flows).every(value=>!value));
const ports=merge({main:{ac_input_power:'sensor.ac',solar_input_power:'sensor.pv1',solar_input_power_2:'sensor.pv2'},auxiliary_1:{output_power:'sensor.out2'},auxiliary_2:{output_power:'sensor.out3'}});
const portStates={'sensor.ac':{state:'100'},'sensor.pv1':{state:'.2',attributes:{unit_of_measurement:'kW'}},'sensor.pv2':{state:'150'},'sensor.out2':{state:'350'},'sensor.out3':{state:'0'}};
let portModel=model(ports,portStates);assert.equal(portModel.main.solar_1,200);assert.equal(portModel.main.solar_2,150);assert.equal(portModel.main.input,450);
assert(portModel.flows.auxiliary_1_main);assert(!portModel.flows.auxiliary_2_main);
portStates['sensor.pv1'].state='unavailable';portModel=model(ports,portStates);assert.equal(portModel.main.input,null);assert.equal(portModel.main.solar_2,150);assert(portModel.flows.auxiliary_1_main);
portStates['sensor.pv1'].state='0';portStates['sensor.pv2'].state='0';portStates['sensor.out2'].state='0';portStates['sensor.out3'].state='350';portModel=model(ports,portStates);assert(!portModel.flows.auxiliary_1_main);assert(portModel.flows.auxiliary_2_main);
ports.main.input_power='sensor.total';portStates['sensor.total']={state:'490'};assert.equal(model(ports,portStates).main.input,490);delete ports.main.input_power;
delete ports.main.solar_input_power;portStates['sensor.pv2'].state='150';assert.equal(model(ports,portStates).main.input,250);
const previousColors=merge({appearance:{solar_color:'#123456'}});assert.equal(previousColors.appearance.auxiliary_1_color,'#123456');assert.equal(previousColors.appearance.auxiliary_2_color,'#123456');
const separateColors=merge({appearance:{solar_color:'#123456',auxiliary_2_color:'#ff8800'}});assert.equal(separateColors.appearance.auxiliary_1_color,'#123456');assert.equal(separateColors.appearance.auxiliary_2_color,'#ff8800');
assert.throws(()=>merge({appearance:{auxiliary_2_color:'not-a-color'}}));
assert.equal(merge({title:undefined,main:{name:undefined},appearance:{main_color:'',duration:undefined,threshold:''}}).title,'Енергопотоки');
assert.equal(merge({main:{name:''}}).main.name,'Головна EcoFlow');
assert.equal(merge({appearance:{main_color:'',duration:undefined,threshold:''}}).appearance.main_color,'#27d9d5');
assert.equal(merge({appearance:{duration:undefined,threshold:''}}).appearance.duration,3);
assert.equal(merge({appearance:{solar_color:'',auxiliary_1_color:''}}).appearance.auxiliary_1_color,'#ffcc42');
assert.equal(merge({appearance:{main_color:'#f00'}}).appearance.main_color,'#f00');
assert.equal(context.window.customCards.length,1);
// Speed follows each route's own wattage, not grid total or a station's XT60 input.
const speedConfig=merge({grid:{power:'sensor.grid',available_entity:'binary_sensor.grid'},auxiliary_1:{input_power:'sensor.a_in',grid_charge_power:'sensor.a_charge',output_power:'sensor.a_out',transfer_power:'sensor.a_transfer'},auxiliary_2:{input_power:'sensor.b_in',output_power:'sensor.b_out'},main:{ac_input_power:'sensor.m_ac',output_power:'sensor.m_out',solar_input_power:'sensor.m_pv'}});
set('binary_sensor.grid','on');set('sensor.grid',1000);set('sensor.a_in',900);set('sensor.a_charge',50);set('sensor.a_out',1000);set('sensor.a_transfer',.15,'kW');set('sensor.b_in',200);set('sensor.b_out',80);set('sensor.m_ac',300);set('sensor.m_pv',600);
assert.deepEqual(JSON.parse(JSON.stringify(model(speedConfig,states).flow_power)),{grid_auxiliary_1:50,grid_auxiliary_2:200,grid_main:300,auxiliary_1_main:150,auxiliary_2_main:80,grid_home:450,main_home:450});
set('binary_sensor.grid','off');set('sensor.m_out',700);assert.equal(model(speedConfig,states).flow_power.main_home,700);
speedConfig.home.power='sensor.home';set('sensor.home',90);assert.equal(model(speedConfig,states).flow_power.main_home,90);
for(const value of [null,undefined,NaN,Infinity,-10,0])assert.equal(flowSpeed(value,3),0);
const speeds=[3.1,10,50,100,500,1000,2400,1000000].map(w=>flowSpeed(w,3));
assert(speeds.every((speed,i)=>Number.isFinite(speed)&&speed>0&&(i===0||speed>speeds[i-1])));
assert(speeds.at(-1)<120);assert.equal(flowSpeed(100,3),100/3);
assert.equal(flowSpeed(500,6),flowSpeed(500,3)/2);
vm.runInContext(source,context);assert.equal(context.window.customCards.length,1);
console.log('PASS: flow topology, per-flow wattage and bounded speed, mutually exclusive home source, unknown states, grid availability, independent transfer flows, two solar ports, color migration, missing data, unit conversion, exact threshold, total input fallback, missing home sensor fallback, input validation, duplicate registration.');

const devices = Array.from({length:20},(_,i)=>({id:`load_${i}`,name:`Load ${i}`,power:20-i}));
const ids = result => Array.from(result).filter(Boolean).map(device=>device.id);
assert.deepEqual(ids(selectConsumers(devices)), ['load_0','load_1','load_2','load_3','load_4','load_5']);
const order = ids(selectConsumers(devices));devices[19].power=100;
const replaced = Array.from(selectConsumers(devices,order));
assert.equal(replaced[5].id,'load_19');assert.deepEqual(ids(replaced).slice(0,5),order.slice(0,5));
devices[5].power=100;
assert(ids(selectConsumers(devices,ids(replaced))).includes('load_19'));
const invalid = [null,0,3,-10,NaN,Infinity].map((power,i)=>({id:`bad_${i}`,power}));assert.deepEqual(ids(selectConsumers(invalid)),[]);
assert.equal(merge({}).consumers.length,0);
assert.throws(()=>merge({consumers:Array.from({length:21},()=>({}))}));
const consumerConfig=merge({consumers:[{name:'Kettle',power:'sensor.kettle',color:'#ff8800'}]});set('sensor.kettle',1.2,'kW');
assert.equal(model(consumerConfig,states).consumers[0].power,1200);assert.equal(model(consumerConfig,states).consumers[0].entity,'sensor.kettle');
set('sensor.kettle',1.2,'kWh');assert.equal(model(consumerConfig,states).consumers[0].power,null);
assert.equal(merge({consumers:[{id:'one'},{id:'one'}]}).consumers.length,2);
assert.notEqual(merge({consumers:[{id:'one'},{id:'one'}]}).consumers[0].id,merge({consumers:[{id:'one'},{id:'one'}]}).consumers[1].id);
console.log('PASS: 20-consumer limit, top six selection, stable tie and slot replacement, invalid and inactive readings, independent consumer power units.');

const sparse=Array.from(selectConsumers(devices,order));
for(const device of devices)device.power=0;devices[2].power=50;devices[4].power=25;
const compact=Array.from(selectConsumers(devices,sparse.map(device=>device?.id)));
assert(compact[0]&&compact[1]&&compact.slice(2).every(device=>device===null));
console.log('PASS: lower-first contiguous slots after inactive consumers disappear');
