const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const source = fs.readFileSync(path.resolve(__dirname, '../suris-ecoflow-flow-card.js'), 'utf8');
const registry = new Map();
const context = { HTMLElement: class {}, window: {}, console: { info() {} }, customElements: { get: key => registry.get(key), define: (key, value) => registry.set(key, value) } };
vm.createContext(context);
vm.runInContext(source.replace('  class SurisEcoFlowFlowCard extends HTMLElement {', '  globalThis.api = { model, merge, readNumber };\n  class SurisEcoFlowFlowCard extends HTMLElement {'), context);
const { model, merge, readNumber } = context.api;
const config = merge({grid:{power:'sensor.grid',available_entity:'binary_sensor.grid',available_state:'on'},auxiliary_1:{input_power:'sensor.a_in',output_power:'sensor.a_out'},auxiliary_2:{input_power:'sensor.b_in',output_power:'sensor.b_out'},main:{input_power:'sensor.m_in',output_power:'sensor.m_out',ac_input_power:'sensor.m_ac',solar_input_power:'sensor.m_pv'},home:{power:'sensor.home',source_entity:'binary_sensor.source',grid_state:'on',main_state:'off'}});
const states = {};
const set = (id, value, unit='W') => states[id] = {state:String(value),attributes:{unit_of_measurement:unit}};
const flow = () => JSON.parse(JSON.stringify(model(config,states).flows));
set('sensor.grid',0);set('binary_sensor.grid','off');set('binary_sensor.source','off');
set('sensor.a_in',0);set('sensor.b_in',0);set('sensor.a_out',150);set('sensor.b_out',200);
set('sensor.m_in',.33,'kW');set('sensor.m_ac',0);set('sensor.m_pv',330);set('sensor.m_out',320);set('sensor.home',320);
assert.deepEqual(flow(),{grid_auxiliary_1:false,grid_auxiliary_2:false,grid_main:false,auxiliary_1_main:true,auxiliary_2_main:true,grid_home:false,main_home:true});
assert.equal(model(config,states).main.input,330);
set('binary_sensor.source','on');set('binary_sensor.grid','on');set('sensor.a_in',100);set('sensor.b_in',200);set('sensor.m_ac',300);
assert(flow().grid_home);assert(!flow().main_home);assert(flow().grid_main);assert(flow().grid_auxiliary_1);assert(flow().grid_auxiliary_2);
for(const state of ['unknown','unavailable','unexpected','']){set('binary_sensor.source',state);assert(!flow().grid_home);assert(!flow().main_home)}
set('binary_sensor.source','off');set('sensor.m_pv','unavailable');assert(!flow().auxiliary_1_main);assert(!flow().auxiliary_2_main);
set('sensor.m_ac','unavailable');assert(!flow().grid_main);assert.equal(model(config,states).main.ac,null);
set('sensor.a_in','unknown');assert(!flow().grid_auxiliary_1);
set('sensor.m_ac',3);assert(!flow().grid_main);set('sensor.m_ac',3.01);assert(flow().grid_main);
set('sensor.m_ac',100);set('sensor.m_pv',200);delete config.main.input_power;assert.equal(model(config,states).main.input,300);
set('sensor.m_pv','unavailable');assert.equal(model(config,states).main.input,null);
set('sensor.m_pv',2,'kWh');assert.equal(model(config,states).main.solar,null);
set('sensor.m_ac',1000,'mW');assert.equal(model(config,states).main.ac,1);
set('sensor.m_ac',.001,'MW');assert.equal(model(config,states).main.ac,1000);
set('sensor.a_in','');assert.equal(readNumber(states,'sensor.a_in',true),null);
set('sensor.a_in',-10);assert(!flow().grid_auxiliary_1);
delete config.home.power;assert(flow().main_home);config.home.power='sensor.home';set('sensor.home','unavailable');assert(!flow().main_home);
assert.throws(()=>merge({home:{grid_state:'on',main_state:'on'}}));
assert.throws(()=>merge({appearance:{threshold:-1}}));assert.throws(()=>merge({appearance:{duration:0}}));assert.throws(()=>merge({appearance:{grid_color:'red'}}));
const blank=model(merge({}),{});assert(Object.values(blank.flows).every(value=>!value));
assert.equal(context.window.customCards.length,1);
vm.runInContext(source,context);assert.equal(context.window.customCards.length,1);
console.log('PASS: flow topology, mutually exclusive home source, unknown states, grid availability, transfer gating, missing data, unit conversion, exact threshold, total input fallback, missing home sensor fallback, input validation, duplicate registration.');
